### ISSUE TITLE
Browse Page 라우팅 및 화면 구성

### ISSUE THREAD

**Issue by profornnan** [boostcamp-2020/Project12-B-Slack-Web#161]
## 💁 설명

Browse Page 라우팅 및 화면 구성

![image](https://user-images.githubusercontent.com/33643752/101708633-04eaba80-3ad1-11eb-9f97-e2bd0151c9f4.png)

## 📑 체크리스트

> 구현해야하는 이슈 체크리스트

- [ ] Browse Page 라우팅
- [ ] Browse Page 화면 구성

## 🚧 주의 사항

> 이슈를 구현할 때 유의깊게 살펴볼 사항

- Browse Channels를 클릭할 경우 Browse Page 화면으로 이동하도록 합니다.
- 기존에 구현해놓은 컴포넌트들을 이용해 Browse Page 화면을 구성합니다.
- `Nocturne` 테마로 진행합니다.

**Comment by Do-ho** [comment]
저랑 테마가 다른 것 같네요...!
![image](https://user-images.githubusercontent.com/33643752/101708633-04eaba80-3ad1-11eb-9f97-e2bd0151c9f4.png)
같이 ```Nocturne``` 테마로 진행하는 건 어떤가요?

**Comment by profornnan** [comment]
넵!! `Nocturne` 테마로 맞춰서 진행해보도록 할게요 😄 이슈 설명에 있는 이미지도 `Nocturne` 테마에 맞춰 변경했습니다.
