### ISSUE TITLE
채팅방 관련 버그 이슈

### ISSUE THREAD

**Issue by profornnan** [boostcamp-2020/Project12-B-Slack-Web#223]
## :warning: 버그 설명

1. URL을 통해 본인이 속해있지 않은 채팅방에 접근할 수 있는 문제
2. Thread가 열린 상태에서 Sidebar를 이용해 다른 채팅방으로 이동이 잘 안되는 문제
3. 채팅방 title이 길면 화면을 넘어가는 문제

## 📑 체크리스트

> 해결해야하는 버그 체크리스트

- [x] URL을 통해 본인이 속해있지 않은 채팅방에 접근할 수 있는 문제
- [x] Thread가 열린 상태에서 Sidebar를 이용해 다른 채팅방으로 이동이 잘 안되는 문제
- [x] 채팅방 title이 길면 화면을 넘어가는 문제

## 🚧 주의 사항

> 버그를 해결할 때 유의깊게 살펴볼 사항

- 2번 버그는 Thread와 Chatroom 컴포넌트의 구조 변경 이후 해결할 예정입니다.

**Comment by Do-ho** [comment]
2번 버그에 대해서 assignee 하겠습니다 ㅎㅎ
